### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by WetzelGabriel** [hxmelab/node-red-contrib-bosch-shc#14]
Hi,
I like your Bosch Smart Home nodes !
would it be possible to get the device name (additionally to deviceId) in msg.topic?
would it be possible to get the temperature and the valve position for each thermostat in msg.topic?
Thank you in advance
Best regards
Gabriel

**Comment by hxmelab** [comment]
Hi Gabriel, thank you for your FR. I will look into that and come back to you soon.

**Comment by philbuettner** [comment]
Hi Gabriel, your FR ist implemented in Version 0.2.15. Feel free to test it. If everything is fine, please close this issue otherwise send me a feedback.

**Comment by hxmelab** [comment]
Hi Gabriel, your FR ist implemented with Version 0.2.15. Feel free to test it. If everything is fine, please close this issue otherwise send me a feedback.
Please check the [release notes](https://github.com/hxmelab/node-red-contrib-bosch-shc#release-notes) for the changes I have done.
