### ISSUE TITLE
Setting RoomClimateControl of TRV (TargetTemperature)

### ISSUE THREAD

**Issue by jensflorian** [hxmelab/node-red-contrib-bosch-shc#19]
Hey hxmelab,

Thanks a lot for your great node RED implementation of the BSH controller! Now I am able to control contact sensors and rollershutters and forward their state in OpenHab using simple flows.

I also own two TRVs. Reading temperature levels from the TRVs works fine. When I try to change their temperature by simple injecting a number like 20, I do not get any response from the TRV except for the output of the current temperature (I tested this in automatic and manual mode of the TRV). Is there anything I have to consider here?

And is there any option to read the TargetTemperature (ie. the number displayed) from the device instead to see whether the injection was accepted?

**Comment by hxmelab** [comment]
Hi jensflorian,

it is indeed not intended to use the TRV directly for setting a temperature. Instead use the service `RoomClimateControl` of the corresponding virtual device with the same name (**-RoomClimateControl-**) to set the temperature of all TRVs in a room at the same time.

To get the temperature which is displayed on a TRV you could do it the same way. Just read the state `setpointTemperature` of the corresponding virtual device **-RoomClimateControl-** from the service `RoomClimateControl`. 

Hope that helps!

**Comment by jensflorian** [comment]
Indeed, using the virtual device instead of the TRV device itself solves the problem (on first attempt it may take some time until the BSHC responds, similar to what I observed when pairing the controller for the first time and retrieving the device list).

Here are the images from my test setup, you may use them for the documentation.

<img width="685" alt="Bildschirmfoto 2020-02-10 um 20 10 13" src="https://user-images.githubusercontent.com/58853392/74182092-aea7b380-4c42-11ea-8b40-191b79ac912b.png">
<img width="500" alt="Bildschirmfoto 2020-02-10 um 20 01 09" src="https://user-images.githubusercontent.com/58853392/74182103-b404fe00-4c42-11ea-8133-d35fd65cae02.png">

I also realized, that the virtual device won't accept numbers outside the 0.5 step values.
Do you think it is possible to adjust the node element to round up or down incorrectly entered values accordingly?

Thank you very much for your help and keep up the great work!

**Comment by philbuettner** [comment]
Alright, thanks for the hint. The input temperature should now get rounded in version 0.2.16.

**Comment by hxmelab** [comment]
Alright, thanks for the hint. The input temperature should now get rounded in version 0.2.16.

**Comment by jensflorian** [comment]
Tested 0.2.16 - works great!
