### ISSUE TITLE
Stop ShutterControl

### ISSUE THREAD

**Issue by DeepHyperspace** [hxmelab/node-red-contrib-bosch-shc#22]
Hi hxmelab,

is it possible to send a Stop-Command to a ShutterControl? I was only able to set a level, but not to interrupt the moving of the shutter.

**Comment by hxmelab** [comment]
I think this should be possible. I'll try to find that out next week.

**Comment by DeepHyperspace** [comment]
There is a property called **payload.state.operationState** if you set this to "STOPPED" the shutter stops. I was able to set that state using ioBroker node and the [ioBroker.bshb](https://github.com/holomekc/ioBroker.bshb/blob/master/README.md) adapter. 

Maybe you can implement that function in your next version :-) thanks in advance 

![2020-02-29 17_07_58-Node-RED _ 192 168 178 65](https://user-images.githubusercontent.com/3355024/75610978-7e9f5200-5b16-11ea-97d0-3c0fe2c78244.png)

**Comment by hxmelab** [comment]
Ok, I added three commands with v0.2.17: open, close, stop 
Could you please test if this is working for you?

**Comment by DeepHyperspace** [comment]
> Ok, I added three commands with v0.2.17: open, close, stop
> Could you please test if this is working for you?

Works perfectly thanks a lot for the quick enhancement 👍
