### ISSUE TITLE
Demo flows

### ISSUE THREAD

**Issue by KeHoSoftware** [hxmelab/node-red-contrib-bosch-shc#27]
Hello Philippe - I had a Skype with Mr. Volker Grahn regarding Node-Red shc today.

https://flows.nodered.org/node/node-red-contrib-bosch-shc

What he misses are the demo flows which you e.g. once here
https://sourcecode.socialcoding.bosch.com/projects/IT/repos/intouch.project.smarthome.nodered.sh/browse/nodes
have filed. These are no longer up to date.

Have you or can you send us a few training or demo nodes at short notice or anchor them in Node-Red ORG
which work with the latest version?
Would be great.
Thank you.

Hallo Philippe – ich hatte heute ein Skype mit Herrn Volker Grahn bezüglich Node-Red shc.

https://flows.nodered.org/node/node-red-contrib-bosch-shc

Was er vermisst sind die Demo Flows welche Ihr z.B. einmal hier
https://sourcecode.socialcoding.bosch.com/projects/IT/repos/intouch.project.smarthome.nodered.sh/browse/nodes
abgelegt habt. Diese sind ja nicht mehr auf dem neusten Stand.

Hast du bzw. kannst du uns kurzfristig ein paar Schulungs bzw. Demo Nodes zusenden bzw. diese in Node-Red ORG verankern 
welche mit der neusten Version arbeiten ?
Wäre prima.
Danke.

**Comment by hxmelab** [comment]
Hi Achim, 

I added some examples which can be found here:
https://flows.nodered.org/flow/01271a01a6b647b7b7cfda67c332cfbc

If you are missing something, just drop me a line here.

Happy testing!
Phil

**Comment by KeHoSoftware** [comment]
Perfect 👌 

Von meinem iPhone gesendet
