### ISSUE TITLE
Add support for BWTH wall thermostat

### ISSUE THREAD

**Issue by jensflorian** [hxmelab/node-red-contrib-bosch-shc#29]
Hello Phil,

Thanks for your great work and adding support for THB (battery powered wall thermostat) with #28 

It is possible to add the mains-powered BWTH devices as well in Node Red? I recently purchased one device. My REST API output:

`        "manufacturer": "BOSCH",
        "roomId": "hz_10",
        "deviceModel": "BWTH",
        "serial": "3014F711A000239BB858E68B",
        "profile": "GENERIC",
        "name": "Thermostat",
        "status": "AVAILABLE",
        "parentDeviceId": "roomClimateControl_hz_10",
        "childDeviceIds": []` 

They also support humidity according to the REST api:
`{
    "@type": "humidityLevelState",
    "humidity": 42.0
}`

I guess extending `function isSupported(model) {` with adding 'BWTH' should do the trick?

Thanks!
jensflorian

**Comment by philbuettner** [comment]
Hi jensflorian,

yes we can extend that function to add the BWTH. Only problem is, I don't have such a device to test it. 

Could you test it then and give me a feedback if it is working properly?

Kind regards
Phil

**Comment by hxmelab** [comment]
Hi jensflorian,

yes we can extend that function to add the BWTH. Only problem is, I don't have such a device to test it.

Could you test it then and give me a feedback if it is working properly?

Kind regards
Phil

**Comment by jensflorian** [comment]
Of course ;-)

EDIT: I manually added 'BWTH' this and restarted my NodeRED. That seems to work. Device is available and data can be accessed.

**Comment by hxmelab** [comment]
Great, project is updated to 0.2.20. If there are any issues regarding the BWTH, just reopen this one. 

Thanks for the hint!
