### ISSUE TITLE
Bosch SHC Connection Problems on node-red-contrib-bosch-shc

### ISSUE THREAD

**Issue by RalJan** [hxmelab/node-red-contrib-bosch-shc#37]
Hello,
I hope I'm in the right place...
I'm trying to connect the SHC Device Node to my SHC Device.
Unfortunately I'm not able to establish a connection.
Everytime I give it try I get the error that the Password isn't correct, eventhough I changed it on both sides.

I hope my problem is somewhat clear.

thx
Ralf

**Comment by hxmelab** [comment]
Hello RalJan,

what system configuration is your Node-RED instance running on?

Kind regards
Phil

**Comment by RalJan** [comment]
Hi Phil,

   HW: Raspberry Pi Model B Rev 2
   OS: Linux raspberrypi 4.19.118+ #1311 Mon Apr 27 14:16:15 BST 2020 armv6l
   Node-Red v1.06

anything missing?

Thx

**Comment by hxmelab** [comment]
Ok, could you please open a terminal and enter 'node-red-log' then try the connection procedure again.

Which node-red-contrib-bosch-shc version do you use and do you use Docker?

**Comment by RalJan** [comment]
strangely enough, after node-red-log it worked...

maybe you can give me a hint, I would like to activate the alarm system depending on the fact if I'm at home or not.
The information if I'm present is determined on the fact if my mobil is present in the WLAN

**Comment by hxmelab** [comment]
Great, first step is done... 

To determine your presence via WiFi you could use the Fritz!Box nodes. They will give you the information if your mobile is connected via WiFi in case you have a Fritz!Box: 
[Fritz Box @ Node-RED](https://flows.nodered.org/search?term=fritz&type=node&type=flow&type=collection)

Otherwise you could use a Nuki smart lock to activate a coming/leaving home scenario locally while locking or unlocking it. 

Hope that helps!
Phil

**Comment by RalJan** [comment]
Yes, wright... thanks  a lot, is the node-red-log necessary all the time?

My problem is not the determination of my presence... I would like to switch the intrusion detection according to that info
off when I'm @ home
on when I'm out

Greeting
Ralf

**Comment by hxmelab** [comment]
You don't need the node-red-log all the time, it's just to print out the errors.

To enable/disable the alarm system you need to select the -IntrusionDetectionSystem- in your device node. Send true/false to that device node to enable/disable the alarm system.
![image](https://user-images.githubusercontent.com/7083309/89163993-c8cda900-d576-11ea-888a-292729d4f7be.png)

Hope that helps!

**Comment by RalJan** [comment]
Hi,
I've got the feeling I'm very close to the final solution...
unfortunately i always get: 
{"@type":"intrusionDetectionControlState"**,"value":"SYSTEM_DISARMED**","triggers":[{"id":"hdm:ZigBee:000d6f000b941963","active":true,"readonly":false}],"actuators":[{"id":"intrusion:visual","active":true,"readonly":false},{"id":"intrusion:push","active":true,"readonly":true}],"armActivationDelayTime":8,"alarmActivationDelayTime":10}

![image](https://user-images.githubusercontent.com/614863/89210754-f8090800-d5c0-11ea-9f0f-aed37d2dbca4.png)

As I'm fairly new to that stuff, sorry for beeing such a pain..
What am I missing?

**Comment by hxmelab** [comment]
Hello RalJan,

I would recommend you to use firefox as browser, because in Chrome the Event Poller checkbox is not displayed.

The configuration of your device node is correct. Please check your inject node. The output should be a boolean.

Hope that helps!
Phil

**Comment by RalJan** [comment]
Hi Phil.
 no... :-(
that switvh node is connected to the device node
![image](https://user-images.githubusercontent.com/614863/89213942-30f7ab80-d5c6-11ea-9fb7-0e5968946558.png)

where 1 == I am @ home
and 0 == I am away

**Comment by hxmelab** [comment]
The switch node just forwards your msg, if the message payloads property NewActive is 1 or 0. Hence, the msg.payload itself contains a property (NewActive) and not a boolean. A device node can not deal with such information. Your intrusion device node expects the msg.payload to be true or false: https://github.com/hxmelab/node-red-contrib-bosch-shc#set-a-state

Hope that helps!
Phil

**Comment by RalJan** [comment]
done!
thanks a lot!!!
