### ISSUE TITLE
Provide room name in the devices msg object

### ISSUE THREAD

**Issue by saemmy** [hxmelab/node-red-contrib-bosch-shc#43]
At the moment the device name is provided in msg.topic. I´m also interested to get the devices room name in the msg object.

What I would like to achieve: an easy way to get all my devices in InfluxDB and have a speaking name and room for all devices. At the moment I have for each single device an extra node and grap the device name from the msg.topic. When I filter for all devices and some specific services I loose the device name, and just have the deviceId. That would be ok, if there would be the possibility in NodeRed to fetch all deviceId and according deviceNames from SHC and same for roome: roomId + roomName.

So may the better solution instead of adding room name to message object would be to have a node for requestion room and device names together with their ids.

**Comment by hxmelab** [comment]
Hi saemmy, 

you will find the roomname of a device in msg.room, after you update to version 0.3.26 and after fetching the device in the device node again. 

Let me know if it is working as you expected.
Cheers Phil
