### ISSUE TITLE
Select devices of a specific type

### ISSUE THREAD

**Issue by saemmy** [hxmelab/node-red-contrib-bosch-shc#44]
Hi, is it possible to get events from all devices of a specific type or device services of a specific type? E.g. get all events of plugs? Or get all events of airquality from twinguards?

**Comment by hxmelab** [comment]
Hi saemmy,

you can select all devices and a specific type to get all messages regarding a specific type. E.g. select all devices and airquality as service to get all airquality values across all twinguards.

Or you can select all services to get all events from a specific device. 

Hope that helps!

**Comment by saemmy** [comment]
Yes thanks.
