### ISSUE TITLE
cannot get /shc/tls

### ISSUE THREAD

**Issue by DaVudu** [hxmelab/node-red-contrib-bosch-shc#52]
On entering shc IP adress and password, I always receive
cannot get /shc/tls
cannot get /shc/id

**Comment by hxmelab** [comment]
Hi DaVudu, which NodeRED version and which node-red-contrib-bosch-shc version are you using?
On what OS is it running?

**Comment by DaVudu** [comment]
Hello,

thanks for your reply. I was able to solve the problem by updating node.js
and node-red to the latest versions. Previously, I was using node.js v8 and
node-red v1.1. Old system on Raspbian, new on Raspberry Pi OS.



Am Sa., 1. Okt. 2022 um 17:17 Uhr schrieb HomeLAB ***@***.***
