### ISSUE TITLE
Get Temperature Level of Device

### ISSUE THREAD

**Issue by derrobin154** [hxmelab/node-red-contrib-bosch-shc#56]
Hey,
on Path "/devices/roomClimateControl_hz_4/services/TemperatureLevel" i only get the temperature that is there in the room. Is it somehow possible to also get the temperature which is currently set?

**Comment by hxmelab** [comment]
You will find it within service RoomClimateControl and state setpointTemperature.

https://apidocs.bosch-smarthome.com/local/#/States/get_devices__deviceId__services_RoomClimateControl_state
