### ISSUE TITLE
Migrate to API 3.2

### ISSUE THREAD

**Issue by sebastianharder** [hxmelab/node-red-contrib-bosch-shc#61]
Support for API 2.x will be dropped later this year.

Please migrate to API 3.2 or later, see https://github.com/BoschSmartHome/bosch-shc-api-docs/blob/master/CHANGELOG.md#320---2022-12-09.

**Comment by hxmelab** [comment]
Thank you for reporting! :)

**Comment by hxmelab** [comment]
Done!
