### ISSUE TITLE
Door/Window sensors not available

### ISSUE THREAD

**Issue by BenniWi** [hxmelab/node-red-contrib-bosch-shc#62]
Hi, 

I'm running the provided node-red docker container with version 3.0.2.
Version of the node-red-contrib-bosch-shc is in version 0.3.28.

I have set up the connection to the bosch smart home controller successfully and the device node discovers all my rooms and my hue lamps. 
Unfortunately I'm not able to find my [door/window sensors](https://www.bosch-smarthome.com/uk/en/products/devices/doorwindow-contact/)

Am I doing something wrong or are the sensors not yet supported?

If it is not yet supported, is it already planned?

**Comment by BenniWi** [comment]
Seems that I just answered my question on my own by checking the [API docs](https://apidocs.bosch-smarthome.com/api_specification.html)

There I do not see any support for the [door/window sensors](https://www.bosch-smarthome.com/uk/en/products/devices/doorwindow-contact/)

Do you agree?

**Comment by hxmelab** [comment]
Hi Benni,

yes, there are indeed major changes in the API and also some new devices. I'll try to update the nodes asap. Probably this or next weekend. 

I'll keep you updated on this channel. 

Thanks for your report!

**Comment by hxmelab** [comment]
The new door/window sensor should now be available in version 0.3.29.

**Comment by BenniWi** [comment]
That's awesome 👍. Thanks a lot. I will test it in the next days.
