### ISSUE TITLE
Bosch REST API 3.2

### ISSUE THREAD

**Issue by werneru** [hxmelab/node-red-contrib-bosch-shc#68]
Bosch changed the REST API from 2.x to 3.2. The node-red-contrib-bosch-shc is no longer working. Please update it.

**Comment by hxmelab** [comment]
Hi Werneru,

thank you for your message. The current version 0.3.29 supports the new local API of the Bosch Controller. Could you please check your version and update it if needed? If the problem still persists, please return here otherwise feel free to close this issue.

Thank you!

**Comment by werneru** [comment]
I'm sorry, yes it seems to work with 0.3.29. Thank you for your work on it!
