### ISSUE TITLE
Pair dosent work

### ISSUE THREAD

**Issue by souljaxaser** [hxmelab/node-red-contrib-bosch-shc#70]
Hello, I have the current Node Red installed on an Intel NUC which also has Home a
Assistant is running. The controller is found in Node Red. Unfortunately, when I try to pair, I get the error (400 Bad Request). Password is correct and I have activated the controller for pairing. Is the error known?

**Comment by hxmelab** [comment]
Hi souljaxaser, I am sorry to hear you have problems to connect. If you still face this issue, please check the following issue:

[https://github.com/hxmelab/node-red-contrib-bosch-shc/issues/42](https://github.com/hxmelab/node-red-contrib-bosch-shc/issues/42)

I am sure you will find a solution here. If not, feel free to reopen this issue and add more details. Thank you!
