### ISSUE TITLE
Not able to pair controller

### ISSUE THREAD

**Issue by thomasjetzinger** [hxmelab/node-red-contrib-bosch-shc#71]
Hello!

I'm running node-red in a docker containner running on a Synology NAS. My Android Smartphone is connected to the controller and everything works properly. 

When I try to pair the node with the controller, I always getting the following error:
![image](https://github.com/hxmelab/node-red-contrib-bosch-shc/assets/103099927/edca0418-5a59-4ca2-b614-7fc5cb987bdb)

What can I do?

**Comment by hxmelab** [comment]
Hi Thomas, did you set your controller in pairing mode with a longpress on the controller button? Same as via the app. If this obvious hint is not the problem, please refer to:
https://github.com/hxmelab/node-red-contrib-bosch-shc/issues/42#issuecomment-1320859782

**Comment by holomekc** [comment]
Small info. If you have the controller II, then it is just a shortpress. This change confused some people in the past already.

**Comment by thomasjetzinger** [comment]
Changed to network mode host and shortpress for paring (thanks to @holomekc )
