### ISSUE TITLE
Pairing fails

### ISSUE THREAD

**Issue by tossa-fan** [hxmelab/node-red-contrib-bosch-shc#72]
Hi,

pairing fails. 

![image](https://github.com/hxmelab/node-red-contrib-bosch-shc/assets/158504921/7c970ff1-843d-4320-a2c1-77d82ce84c71)

I do not imagine why. 

Can you help? I read all posts related to this and could not find an answer.

Running in docker container on Synology NAS.

Best regards, tossa-fan

**Comment by holomekc** [comment]
Hi,

this sounds like you used the wrong password.

Br,
Chris

**Comment by tossa-fan** [comment]
No, the password is correct. I even set it to a simple numeric one to be sure it does not fail.

**Comment by tossa-fan** [comment]
Ok, after trying almost everything - i have redeployed node-red and setup everything from scratch - now it works. Strange. But ok for now. :-)
