### ISSUE TITLE
Node red do not start after update bosch-shc

### ISSUE THREAD

**Issue by michaeldoll** [hxmelab/node-red-contrib-bosch-shc#74]
Hello,
I have the following problem:
After updating the node, node red no longer starts. 
Below is the log output at startup
What can I do to make node-red start again?

Microsoft Windows [Version 10.0.22631.3296]
(c) Microsoft Corporation. Alle Rechte vorbehalten.

C:\Users\micha>cd appdata

C:\Users\micha\AppData>cd roaming

C:\Users\micha\AppData\Roaming>cd npm

C:\Users\micha\AppData\Roaming\npm>node.red.cmd
Der Befehl "node.red.cmd" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.

C:\Users\micha\AppData\Roaming\npm>node-red.cmd
4 Apr 14:38:18 - [info]

Welcome to Node-RED
===================

4 Apr 14:38:18 - [info] Node-RED version: v3.0.2
4 Apr 14:38:18 - [info] Node.js  version: v14.15.4
4 Apr 14:38:18 - [info] Windows_NT 10.0.22631 x64 LE
4 Apr 14:38:19 - [info] Loading palette nodes
4 Apr 14:38:19 - [debug] Module: @alainx277/node-red-miele 0.1.0 \Users\micha\.node-red\node_modules\@alainx277\node-red-miele
4 Apr 14:38:19 - [debug] Module: @rotflorg/node-red-contrib-ecoflow-powerstream 0.5.1 \Users\micha\.node-red\node_modules\@rotflorg\node-red-contrib-ecoflow-powerstream
4 Apr 14:38:19 - [debug] Module: google-translate-tts 0.4.0-dev \Users\micha\.node-red\node_modules\google-translate-tts
4 Apr 14:38:19 - [debug] Module: node-red-contrib-boolean-logic 0.0.3 \Users\micha\.node-red\node_modules\node-red-contrib-boolean-logic
4 Apr 14:38:19 - [debug] Module: node-red-contrib-boolean-logic-ultimate 1.0.56 \Users\micha\.node-red\node_modules\node-red-contrib-boolean-logic-ultimate
4 Apr 14:38:19 - [debug] Module: node-red-contrib-bosch-shc 0.4.31 \Users\micha\.node-red\node_modules\node-red-contrib-bosch-shc
4 Apr 14:38:19 - [debug] Module: node-red-contrib-buffer-parser 3.2.2 \Users\micha\.node-red\node_modules\node-red-contrib-buffer-parser
4 Apr 14:38:19 - [debug] Module: node-red-contrib-calc 1.0.5 \Users\micha\.node-red\node_modules\node-red-contrib-calc
4 Apr 14:38:19 - [debug] Module: node-red-contrib-color-convert 0.0.8 \Users\micha\.node-red\node_modules\node-red-contrib-color-convert
4 Apr 14:38:19 - [debug] Module: node-red-contrib-colorspace 1.0.2 \Users\micha\.node-red\node_modules\node-red-contrib-colorspace
4 Apr 14:38:19 - [debug] Module: node-red-contrib-credentials 0.2.2 \Users\micha\.node-red\node_modules\node-red-contrib-credentials
4 Apr 14:38:19 - [debug] Module: node-red-contrib-dashboard-bar-chart-data 0.9.8 \Users\micha\.node-red\node_modules\node-red-contrib-dashboard-bar-chart-data
4 Apr 14:38:19 - [debug] Module: node-red-contrib-daylight-rgbw 2.1.7 \Users\micha\.node-red\node_modules\node-red-contrib-daylight-rgbw
4 Apr 14:38:19 - [debug] Module: node-red-contrib-ecoflow 0.9.7 \Users\micha\.node-red\node_modules\node-red-contrib-ecoflow
4 Apr 14:38:19 - [debug] Module: node-red-contrib-enocean 0.8.5 \Users\micha\.node-red\node_modules\node-red-contrib-enocean
4 Apr 14:38:19 - [debug] Module: node-red-contrib-enocean-esp2 0.0.6 \Users\micha\.node-red\node_modules\node-red-contrib-enocean-esp2
4 Apr 14:38:19 - [debug] Module: node-red-contrib-enocean-telegram-decoder 1.0.1 \Users\micha\.node-red\node_modules\node-red-contrib-enocean-telegram-decoder
4 Apr 14:38:19 - [debug] Module: node-red-contrib-enoceanip 0.1.2 \Users\micha\.node-red\node_modules\node-red-contrib-enoceanip
4 Apr 14:38:19 - [debug] Module: node-red-contrib-float 1.0.3 \Users\micha\.node-red\node_modules\node-red-contrib-float
4 Apr 14:38:19 - [debug] Module: node-red-contrib-full-msg-json-schema-validation 1.1.0 \Users\micha\.node-red\node_modules\node-red-contrib-full-msg-json-schema-validation
4 Apr 14:38:19 - [debug] Module: node-red-contrib-geofox-api 0.1.3 \Users\micha\.node-red\node_modules\node-red-contrib-geofox-api
4 Apr 14:38:19 - [debug] Module: node-red-contrib-homekit-rgb 1.0.3 \Users\micha\.node-red\node_modules\node-red-contrib-homekit-rgb
4 Apr 14:38:19 - [debug] Module: node-red-contrib-hue-tunable-white 1.1.1 \Users\micha\.node-red\node_modules\node-red-contrib-hue-tunable-white
4 Apr 14:38:19 - [debug] Module: node-red-contrib-huemagic 4.2.2 \Users\micha\.node-red\node_modules\node-red-contrib-huemagic
4 Apr 14:38:19 - [debug] Module: node-red-contrib-influxdb 0.6.1 \Users\micha\.node-red\node_modules\node-red-contrib-influxdb
4 Apr 14:38:19 - [debug] Module: node-red-contrib-jsonfilter 0.1.0 \Users\micha\.node-red\node_modules\node-red-contrib-jsonfilter
4 Apr 14:38:19 - [debug] Module: node-red-contrib-light 1.0.0 \Users\micha\.node-red\node_modules\node-red-contrib-light
4 Apr 14:38:19 - [debug] Module: node-red-contrib-modbus 5.26.0 \Users\micha\.node-red\node_modules\node-red-contrib-modbus
4 Apr 14:38:19 - [debug] Module: node-red-contrib-modbustcp 1.2.3 \Users\micha\.node-red\node_modules\node-red-contrib-modbustcp
4 Apr 14:38:19 - [debug] Module: node-red-contrib-skyremote-new 0.1.2 \Users\micha\.node-red\node_modules\node-red-contrib-skyremote-new
4 Apr 14:38:19 - [debug] Module: node-red-contrib-sonospollytts 2.0.8 \Users\micha\.node-red\node_modules\node-red-contrib-sonospollytts
4 Apr 14:38:19 - [debug] Module: node-red-contrib-state 1.6.1 \Users\micha\.node-red\node_modules\node-red-contrib-state
4 Apr 14:38:19 - [debug] Module: node-red-contrib-sum 0.1.1 \Users\micha\.node-red\node_modules\node-red-contrib-sum
4 Apr 14:38:19 - [debug] Module: node-red-contrib-sun-position 2.2.0-beta3 \Users\micha\.node-red\node_modules\node-red-contrib-sun-position
4 Apr 14:38:19 - [debug] Module: node-red-contrib-tofloat 1.0.0 \Users\micha\.node-red\node_modules\node-red-contrib-tofloat
4 Apr 14:38:19 - [debug] Module: node-red-contrib-tts-ultimate 1.0.50 \Users\micha\.node-red\node_modules\node-red-contrib-tts-ultimate
4 Apr 14:38:19 - [debug] Module: node-red-contrib-tuya-smart-device 5.1.0 \Users\micha\.node-red\node_modules\node-red-contrib-tuya-smart-device
4 Apr 14:38:19 - [debug] Module: node-red-contrib-ui-iro-color-picker 0.1.6 \Users\micha\.node-red\node_modules\node-red-contrib-ui-iro-color-picker
4 Apr 14:38:19 - [debug] Module: node-red-dashboard 3.5.0 \Users\micha\.node-red\node_modules\node-red-dashboard
4 Apr 14:38:19 - [debug] Module: node-red-node-openweathermap 0.5.1 \Users\micha\.node-red\node_modules\node-red-node-openweathermap
4 Apr 14:38:19 - [debug] Module: node-red-node-random 0.4.1 \Users\micha\.node-red\node_modules\node-red-node-random
4 Apr 14:38:19 - [debug] Module: node-red-node-serialport 1.0.3 \Users\micha\.node-red\node_modules\node-red-node-serialport
4 Apr 14:38:19 - [debug] Module: node-red-node-tail 0.3.2 \Users\micha\.node-red\node_modules\node-red-node-tail
4 Apr 14:38:19 - [debug] Module: nr-strompreis 1.0.0 \Users\micha\.node-red\node_modules\nr-strompreis
4 Apr 14:38:19 - [debug] Module: json-db-node-red 0.5.3 C:\Users\micha\node_modules\json-db-node-red
4 Apr 14:38:19 - [debug] ! Module: node-red-contrib-bosch-shc 0.3.25 C:\Users\micha\node_modules\node-red-contrib-bosch-shc *ignored due to local copy*
4 Apr 14:38:19 - [debug] Module: node-red-contrib-json 0.2.0 C:\Users\micha\node_modules\node-red-contrib-json
4 Apr 14:38:22 - [info] Dashboard version 3.5.0 started at /ui
4 Apr 14:38:22 - [info] Settings file  : C:\Users\micha\.node-red\settings.js
4 Apr 14:38:22 - [info] Context store  : 'default' [module=localfilesystem]
4 Apr 14:38:22 - [info] User directory : \Users\micha\.node-red
4 Apr 14:38:22 - [warn] Projects disabled : editorTheme.projects.enabled=false
4 Apr 14:38:22 - [warn] Flows file name not set. Generating name using hostname.
4 Apr 14:38:22 - [info] Flows file     : \Users\micha\.node-red\flows_WSMD01.json
4 Apr 14:38:22 - [debug] loaded flow revision: 7583d62c8f1ceb5c27e2e0a21544fa69
4 Apr 14:38:22 - [debug] red/runtime/nodes/credentials.load : no user key present
4 Apr 14:38:22 - [debug] red/runtime/nodes/credentials.load : using default key
4 Apr 14:38:22 - [debug] red/runtime/nodes/credentials.load : keyType=system
4 Apr 14:38:22 - [warn]

---------------------------------------------------------------------
Your flow credentials file is encrypted using a system-generated key.

If the system-generated key is lost for any reason, your credentials
file will not be recoverable, you will have to delete it and re-enter
your credentials.

You should set your own key using the 'credentialSecret' option in
your settings file. Node-RED will then re-encrypt your credentials
file using your chosen key the next time you deploy a change.
---------------------------------------------------------------------

4 Apr 14:38:22 - [info] Server now running at http://127.0.0.1:1880/
4 Apr 14:38:22 - [info] Starting flows
4 Apr 14:38:22 - [debug] red/nodes/flows.start : starting flow : global
4 Apr 14:38:22 - [debug] red/nodes/flows.start : starting flow : 593a85b4.6a767c
4 Apr 14:38:22 - [debug] red/nodes/flows.start : starting flow : 32f6f8da36fc32c4
4 Apr 14:38:22 - [debug] red/nodes/flows.start : starting flow : e0af9963.0d7968
4 Apr 14:38:22 - [debug] red/nodes/flows.start : starting flow : 4c782aa344103c77
4 Apr 14:38:22 - [debug] red/nodes/flows.start : starting flow : f3f675617868bd08
4 Apr 14:38:22 - [debug] red/nodes/flows.start : starting flow : 3517b1eac4a6f855
4 Apr 14:38:22 - [debug] red/nodes/flows.start : starting flow : 25ed9911.fab896
4 Apr 14:38:22 - [debug] red/nodes/flows.start : starting flow : 7e16d47e.426bec
4 Apr 14:38:22 - [debug] red/nodes/flows.start : starting flow : 3968c7e3.f7c908
4 Apr 14:38:22 - [debug] red/nodes/flows.start : starting flow : 89d61cf.f984ae
4 Apr 14:38:22 - [debug] red/nodes/flows.start : starting flow : c61d4a81.eb89f8
4 Apr 14:38:22 - [debug] red/nodes/flows.start : starting flow : b759a05d.b66c5
4 Apr 14:38:22 - [debug] red/nodes/flows.start : starting flow : 6b15d3b0.d6b42c
4 Apr 14:38:22 - [debug] red/nodes/flows.start : starting flow : ca7c2a8c26593921
4 Apr 14:38:22 - [debug] red/nodes/flows.start : starting flow : 047cabf3b01a38b4
4 Apr 14:38:22 - [debug] red/nodes/flows.start : starting flow : e96a871b3627b615
4 Apr 14:38:22 - [debug] red/nodes/flows.start : starting flow : 82fe13c52934dda0
4 Apr 14:38:22 - [debug] red/nodes/flows.start : starting flow : 2d80d0e879331701
4 Apr 14:38:22 - [debug] red/nodes/flows.start : starting flow : 511dbef953fcdc92
4 Apr 14:38:22 - [debug] red/nodes/flows.start : starting flow : d9df8445fff9cd76
4 Apr 14:38:22 - [debug] red/nodes/flows.start : starting flow : 83cc87bb0d227cfe
4 Apr 14:38:22 - [debug] red/nodes/flows.start : starting flow : 50b3e16823bf05ab
4 Apr 14:38:22 - [debug] red/nodes/flows.start : starting flow : 8af171e5c452924a
4 Apr 14:38:22 - [debug] red/nodes/flows.start : not starting disabled flow : e0dd44b7.b17f88
4 Apr 14:38:22 - [debug] red/nodes/flows.start : starting flow : a6d29d13.3c30c
4 Apr 14:38:22 - [debug] red/nodes/flows.start : starting flow : 7bfc25e6d0f5de5e
4 Apr 14:38:22 - [info] [miele-config:Waschmaschine] Fetching Miele API token
4 Apr 14:38:22 - [info] [miele-config:Waschmaschine] Authenticated with Miele API
4 Apr 14:38:22 - [debug] [inject:cb3d7d284a9e7b76] repeat = 3600000
4 Apr 14:38:22 - [debug] [inject:967e8805.289488] repeat = 10000
4 Apr 14:38:22 - [debug] [inject:4da80c5c97c57659] repeat = 20000
4 Apr 14:38:22 - [debug] [inject:bfc20ae1fce10669] repeat = 10000
4 Apr 14:38:22 - [debug] [inject:50a081b9a5b24bba] repeat = 15000
4 Apr 14:38:22 - [debug] [inject:a0a8da6c8c26c701] repeat = 15000
4 Apr 14:38:22 - [debug] [inject:6ec4ee28da2d7028] repeat = 10000
4 Apr 14:38:22 - [debug] [inject:dbecab38996ec535] repeat = 15000
4 Apr 14:38:22 - [info] Started flows
(node:21960) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `node --trace-warnings ...` to show where the warning was created)
4 Apr 14:38:22 - [debug] [inject:c0629413c3ca6379] repeat = 300000
4 Apr 14:38:22 - [info] [enocean-config-node:240c5ec1127cd57d] port opened
4 Apr 14:38:22 - [info] [enocean-config-node:240c5ec1127cd57d] Your BaseID is fffdd380
4 Apr 14:38:22 - [info] [mqtt-broker:Ecoflow mqtt] Connected to broker: ANDROID_FF12A24A-B3D1-3719-9314-DF617C735742_1526082573203865602@mqtts://mqtt.ecoflow.com
4 Apr 14:38:23 - [info] [mqtt-broker:supla] Connected to broker: mqtts://mqtt66.supla.org:8883
(node:21960) UnhandledPromiseRejectionWarning: Error: Request failed with status code 401
    at createError (C:\Users\micha\.node-red\node_modules\axios\lib\core\createError.js:16:15)
    at settle (C:\Users\micha\.node-red\node_modules\axios\lib\core\settle.js:17:12)
    at IncomingMessage.handleStreamEnd (C:\Users\micha\.node-red\node_modules\axios\lib\adapters\http.js:322:11)
    at IncomingMessage.emit (events.js:327:22)
    at IncomingMessage.EventEmitter.emit (domain.js:467:12)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
(node:21960) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:21960) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
4 Apr 14:38:23 - [info] [shc-config:9ecabc82.cab5] Long polling SHC: 192.168.2.108 with poll Id: fd7hd7jhi-5
4 Apr 14:38:27 - [debug] [inject:ac33f8c010b28004] repeat = 10000
4 Apr 14:38:27 - [debug] [inject:6eb2b29fd90f14f4] repeat = 15000
4 Apr 14:38:27 - [debug] [inject:01005674b4435c67] repeat = 30000
4 Apr 14:38:28 - [red] Uncaught Exception:
4 Apr 14:38:28 - [error] TypeError: Object.hasOwn is not a function
    at SHCDeviceNode.setMsgObject (C:\Users\micha\.node-red\node_modules\node-red-contrib-bosch-shc\nodes\shc-device.js:111:42)
    at Object.next (C:\Users\micha\.node-red\node_modules\node-red-contrib-bosch-shc\nodes\shc-device.js:81:47)
    at ConsumerObserver.next (C:\Users\micha\.node-red\node_modules\rxjs\src\internal\Subscriber.ts:161:25)
    at SafeSubscriber.Subscriber._next (C:\Users\micha\.node-red\node_modules\rxjs\src\internal\Subscriber.ts:119:22)
    at SafeSubscriber.Subscriber.next (C:\Users\micha\.node-red\node_modules\rxjs\src\internal\Subscriber.ts:75:12)
    at IncomingMessage.<anonymous> (C:\Users\micha\.node-red\node_modules\bosch-smart-home-bridge\dist\api\abstract-bshc-client.js:152:38)
    at IncomingMessage.emit (events.js:327:22)
    at IncomingMessage.EventEmitter.emit (domain.js:467:12)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)

C:\Users\micha\AppData\Roaming\npm>

**Comment by hxmelab** [comment]
Hi Michael,

thank you for reporting this issue. Due to your node.js version v14.15.4 the following error occurs  (from you logs)

4 Apr 14:38:28 - [error] TypeError: Object.hasOwn is not a function

because Object.hasOwn is only available since node.js v16.9.0.

Is it possible for you to update your node.js version? This would be the fast solution.

**Comment by hxmelab** [comment]
Should be fixed with version 0.4.32.
